FROM python:3.11-slim

WORKDIR /app

# Copiar requirements.txt desde la raíz
COPY requirements.txt .

# Instalar dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Copiar todo el src/ al contenedor
COPY mlops_pipeline/src/ .

EXPOSE 8000

CMD ["uvicorn", "model_deploy:app", "--host", "0.0.0.0", "--port", "8000"]